import type { Metadata } from "next";
import "./globals.css";
import GradualBlur from '@/components/reactbits/gradual';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <section className="relative min-h-screen overflow-hidden">
          {/* Scrollable content */}
          <div className="h-full">
            {children}
          </div>

          {/* Gradual Blur fixed di bottom */}
          <div className="fixed bottom-0 left-0 w-full pointer-events-none">
            <GradualBlur
              target="parent"
              position="bottom"
              height="6rem"
              strength={2}
              divCount={5}
              curve="bezier"
              exponential={true}
              opacity={1}
            />
          </div>
        </section>
      </body>
    </html>
  );
}
